CREATE DATABASE IF NOT EXISTS leads_monitoring;
USE leads_monitoring;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('admin', 'karyawan') NOT NULL DEFAULT 'karyawan',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wilayah (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_wilayah VARCHAR(100) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sumber_leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_sumber VARCHAR(100) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  wilayah_id INT NOT NULL,
  sumber_id INT NOT NULL,
  user_id INT NOT NULL,
  tanggal DATE NOT NULL,
  jumlah INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (wilayah_id) REFERENCES wilayah(id) ON DELETE RESTRICT,
  FOREIGN KEY (sumber_id) REFERENCES sumber_leads(id) ON DELETE RESTRICT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
